# import locale
# locale.setlocale(locale.LC_ALL, 'pt_BR.utf8')
from datetime import datetime
import requests

from django.contrib import admin
from django.forms import Select, Textarea
from django.utils.html import format_html
from config.mixins import AuditoriaAdmin, AuditoriaAdminTabularInline, AuditoriaAdminStackedInline

from .models import (
    DashboardsReceitasDespesas,
    DashboardsReceitas,
    DashboardsDespesas,
)



@admin.register(DashboardsReceitasDespesas)
class DashboardsReceitasDespesasAdmin(AuditoriaAdmin):
    actions = []
    search_fields = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'valor_previsto',
        'valor_arrecadado_realizado',
        'valor_arrecadado_anulado',
        'valor_arrecadado',
        'valor_arrecadado_realizado_total',
        'valor_arrecadado_anulado_total',
        'valor_arrecadado_total',
        'valor_lei',
        'valor_dotacao_suplementacao',
        'valor_dotacao_anulacao',
        'valor_lei_credito',
        'valor_empenhado_realizado',
        'valor_empenhado_anulado',
        'valor_empenhado',
        'valor_liquidado_realizado',
        'valor_liquidado_estornado',
        'valor_liquidado',
        'valor_pago_realizado',
        'valor_pago_estornado',
        'valor_pago',
        'valor_saldo_dotacao',
        'valor_dotacao_suplementacao_total',
        'valor_dotacao_anulacao_total',
        'valor_lei_credito_total',
        'valor_empenhado_realizado_total',
        'valor_empenhado_anulado_total',
        'valor_empenhado_total',
        'valor_liquidado_realizado_total',
        'valor_liquidado_estornado_total',
        'valor_liquidado_total',
        'valor_pago_realizado_total',
        'valor_pago_estornado_total',
        'valor_pago_total',
    )
    list_filter = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'valor_previsto',
        'valor_arrecadado_realizado',
        'valor_arrecadado_anulado',
        'valor_arrecadado',
        'valor_arrecadado_realizado_total',
        'valor_arrecadado_anulado_total',
        'valor_arrecadado_total',
        'valor_lei',
        'valor_dotacao_suplementacao',
        'valor_dotacao_anulacao',
        'valor_lei_credito',
        'valor_empenhado_realizado',
        'valor_empenhado_anulado',
        'valor_empenhado',
        'valor_liquidado_realizado',
        'valor_liquidado_estornado',
        'valor_liquidado',
        'valor_pago_realizado',
        'valor_pago_estornado',
        'valor_pago',
        'valor_saldo_dotacao',
        'valor_dotacao_suplementacao_total',
        'valor_dotacao_anulacao_total',
        'valor_lei_credito_total',
        'valor_empenhado_realizado_total',
        'valor_empenhado_anulado_total',
        'valor_empenhado_total',
        'valor_liquidado_realizado_total',
        'valor_liquidado_estornado_total',
        'valor_liquidado_total',
        'valor_pago_realizado_total',
        'valor_pago_estornado_total',
        'valor_pago_total',
    )
    list_display = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'valor_previsto',
        'valor_arrecadado_realizado',
        'valor_arrecadado_anulado',
        'valor_arrecadado',
        'valor_arrecadado_realizado_total',
        'valor_arrecadado_anulado_total',
        'valor_arrecadado_total',
        'valor_lei',
        'valor_dotacao_suplementacao',
        'valor_dotacao_anulacao',
        'valor_lei_credito',
        'valor_empenhado_realizado',
        'valor_empenhado_anulado',
        'valor_empenhado',
        'valor_liquidado_realizado',
        'valor_liquidado_estornado',
        'valor_liquidado',
        'valor_pago_realizado',
        'valor_pago_estornado',
        'valor_pago',
        'valor_saldo_dotacao',
        'valor_dotacao_suplementacao_total',
        'valor_dotacao_anulacao_total',
        'valor_lei_credito_total',
        'valor_empenhado_realizado_total',
        'valor_empenhado_anulado_total',
        'valor_empenhado_total',
        'valor_liquidado_realizado_total',
        'valor_liquidado_estornado_total',
        'valor_liquidado_total',
        'valor_pago_realizado_total',
        'valor_pago_estornado_total',
        'valor_pago_total',
    )
    readonly_fields = AuditoriaAdmin.readonly_fields + (
    )
    inlines = [
    ]



@admin.register(DashboardsReceitas)
class DashboardsReceitasAdmin(AuditoriaAdmin):
    actions = []
    search_fields = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'receita_categoria_economica',
        'receita_origem',
        'receita_especie',
        'receita_rubrica',
        'receita_alinea',
        'receita_sub_alinea',
        'valor_previsto',
        'valor_arrecadado_realizado',
        'valor_arrecadado_anulado',
        'valor_arrecadado',
        'valor_arrecadado_realizado_total',
        'valor_arrecadado_anulado_total',
        'valor_arrecadado_total',
    )
    list_filter = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'receita_categoria_economica',
        'receita_origem',
        'receita_especie',
        'receita_rubrica',
        'receita_alinea',
        'receita_sub_alinea',
        'valor_previsto',
        'valor_arrecadado_realizado',
        'valor_arrecadado_anulado',
        'valor_arrecadado',
        'valor_arrecadado_realizado_total',
        'valor_arrecadado_anulado_total',
        'valor_arrecadado_total',
    )
    list_display = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'receita_categoria_economica',
        'receita_origem',
        'receita_especie',
        'receita_rubrica',
        'receita_alinea',
        'receita_sub_alinea',
        'valor_previsto',
        'valor_arrecadado_realizado',
        'valor_arrecadado_anulado',
        'valor_arrecadado',
        'valor_arrecadado_realizado_total',
        'valor_arrecadado_anulado_total',
        'valor_arrecadado_total',
    )
    readonly_fields = AuditoriaAdmin.readonly_fields + (
    )
    inlines = [
    ]



@admin.register(DashboardsDespesas)
class DashboardsDespesasAdmin(AuditoriaAdmin):
    actions = []
    search_fields = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'funcao',
        'sub_funcao',
        'programa',
        'acao',
        'acao_tipo',
        'despesa_categoria_economica',
        'despesa_grupo_natureza',
        'despesa_modalidade_aplicacao',
        'despesa_elemento_despesa',
        'valor_lei',
        'valor_dotacao_suplementacao',
        'valor_dotacao_anulacao',
        'valor_lei_credito',
        'valor_empenhado_realizado',
        'valor_empenhado_anulado',
        'valor_empenhado',
        'valor_liquidado_realizado',
        'valor_liquidado_estornado',
        'valor_liquidado',
        'valor_pago_realizado',
        'valor_pago_estornado',
        'valor_pago',
        'valor_saldo_dotacao',
        'valor_dotacao_suplementacao_total',
        'valor_dotacao_anulacao_total',
        'valor_lei_credito_total',
        'valor_empenhado_realizado_total',
        'valor_empenhado_anulado_total',
        'valor_empenhado_total',
        'valor_liquidado_realizado_total',
        'valor_liquidado_estornado_total',
        'valor_liquidado_total',
        'valor_pago_realizado_total',
        'valor_pago_estornado_total',
        'valor_pago_total',
    )
    list_filter = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'funcao',
        'sub_funcao',
        'programa',
        'acao',
        'acao_tipo',
        'despesa_categoria_economica',
        'despesa_grupo_natureza',
        'despesa_modalidade_aplicacao',
        'despesa_elemento_despesa',
        'valor_lei',
        'valor_dotacao_suplementacao',
        'valor_dotacao_anulacao',
        'valor_lei_credito',
        'valor_empenhado_realizado',
        'valor_empenhado_anulado',
        'valor_empenhado',
        'valor_liquidado_realizado',
        'valor_liquidado_estornado',
        'valor_liquidado',
        'valor_pago_realizado',
        'valor_pago_estornado',
        'valor_pago',
        'valor_saldo_dotacao',
        'valor_dotacao_suplementacao_total',
        'valor_dotacao_anulacao_total',
        'valor_lei_credito_total',
        'valor_empenhado_realizado_total',
        'valor_empenhado_anulado_total',
        'valor_empenhado_total',
        'valor_liquidado_realizado_total',
        'valor_liquidado_estornado_total',
        'valor_liquidado_total',
        'valor_pago_realizado_total',
        'valor_pago_estornado_total',
        'valor_pago_total',
    )
    list_display = (
        'ano',
        'mes',
        'ano_mes',
        'orgao',
        'unidade_orcamentaria',
        'fonte',
        'funcao',
        'sub_funcao',
        'programa',
        'acao',
        'acao_tipo',
        'despesa_categoria_economica',
        'despesa_grupo_natureza',
        'despesa_modalidade_aplicacao',
        'despesa_elemento_despesa',
        'valor_lei',
        'valor_dotacao_suplementacao',
        'valor_dotacao_anulacao',
        'valor_lei_credito',
        'valor_empenhado_realizado',
        'valor_empenhado_anulado',
        'valor_empenhado',
        'valor_liquidado_realizado',
        'valor_liquidado_estornado',
        'valor_liquidado',
        'valor_pago_realizado',
        'valor_pago_estornado',
        'valor_pago',
        'valor_saldo_dotacao',
        'valor_dotacao_suplementacao_total',
        'valor_dotacao_anulacao_total',
        'valor_lei_credito_total',
        'valor_empenhado_realizado_total',
        'valor_empenhado_anulado_total',
        'valor_empenhado_total',
        'valor_liquidado_realizado_total',
        'valor_liquidado_estornado_total',
        'valor_liquidado_total',
        'valor_pago_realizado_total',
        'valor_pago_estornado_total',
        'valor_pago_total',
    )
    readonly_fields = AuditoriaAdmin.readonly_fields + (
    )
    inlines = [
    ]