# Generated by Django 3.2 on 2022-03-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Título')),
                ('valor_fixado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Fixado')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acoes_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
            },
        ),
        migrations.CreateModel(
            name='ElementosDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='elementosdespesa_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento de Despesa',
                'verbose_name_plural': 'Elementos de Despesa',
            },
        ),
        migrations.CreateModel(
            name='Fontes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fontes_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fonte',
                'verbose_name_plural': 'Fontes',
            },
        ),
        migrations.CreateModel(
            name='Funcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcoes_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcoes_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
            },
        ),
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('num_lei', models.CharField(max_length=20, verbose_name='Número da Lei')),
                ('ano_exercicio', models.IntegerField(verbose_name='Ano de Exercício')),
                ('data_aprovacao', models.DateField(verbose_name='Data de Aprovação da LOA')),
                ('data_envio', models.DateField(verbose_name='Data de Envio da LOA')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação da LOA')),
                ('percentual_suplementacao', models.CharField(max_length=20, verbose_name='Percentual de Suplementação do Orçamento')),
                ('valor_total_fixado_orcamento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total Fixado no Orçamento')),
                ('valor_total_suplementacao_orcamento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total de Suplementação no Orçamento')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orcamentos_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lei Orçamentária Anual',
                'verbose_name_plural': 'Lei Orçamentária Anual',
            },
        ),
        migrations.CreateModel(
            name='Orgaos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgaos_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orgaos_orcamento', to='planejamento.orcamentos')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
            },
        ),
        migrations.CreateModel(
            name='PlanoPluriAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('num_lei', models.CharField(max_length=20, verbose_name='Número da Lei')),
                ('ano_inicio', models.CharField(max_length=4, verbose_name='Ano de Início')),
                ('ano_termino', models.CharField(max_length=4, verbose_name='Ano de Término')),
                ('data_aprovacao', models.DateField(verbose_name='Data de Aprovação do PPA')),
                ('data_envio', models.DateField(verbose_name='Data de Envio da PPA')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação da PPA')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planoplurianual_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planoplurianual_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlanoPluriAnual',
                'verbose_name_plural': 'PlanoPluriAnual',
            },
        ),
        migrations.CreateModel(
            name='UnidadesOrcamentarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidadesorcamentarias_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidadesorcamentarias_orcamento', to='planejamento.orcamentos')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidadesorcamentarias_orgao', to='planejamento.orgaos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidadesorcamentarias_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidade Orçamentária',
                'verbose_name_plural': 'Unidades Orçamentárias',
            },
        ),
        migrations.CreateModel(
            name='UnidadesGestoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('codigo_credor', models.CharField(max_length=50, verbose_name='Código do Credor')),
                ('poder', models.CharField(max_length=50, verbose_name='Poder')),
                ('sigla', models.CharField(max_length=50, verbose_name='Sigla')),
                ('tipo_administracao', models.CharField(max_length=50, verbose_name='Tipo de Administração')),
                ('tipo_unidade_gestora', models.IntegerField(choices=[(1, 'Nao Definido')], verbose_name='Tipo de Unidade Gestora')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidadesgestoras_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidadesgestoras_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidadesgestoras_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidade Gestora',
                'verbose_name_plural': 'Unidades Gestoras',
            },
        ),
        migrations.CreateModel(
            name='SubFuncoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subfuncoes_created_by', to=settings.AUTH_USER_MODEL)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subfuncoes_funcao', to='planejamento.funcoes')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subfuncoes_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-Função',
                'verbose_name_plural': 'Sub-Funções',
            },
        ),
        migrations.CreateModel(
            name='SubAlineas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subalineas_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subalineas_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subalineas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-Alínea',
                'verbose_name_plural': 'Sub-Alíneas',
            },
        ),
        migrations.CreateModel(
            name='Secretarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secretarias_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretarias_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secretarias_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.CreateModel(
            name='Rubricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('titulo', models.TextField(verbose_name='Titulo')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rubricas_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubricas_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rubricas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rubrica',
                'verbose_name_plural': 'Rubricas',
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programas_created_by', to=settings.AUTH_USER_MODEL)),
                ('planoplurianual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_planoplurianual', to='planejamento.planoplurianual')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Origens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='origens_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origens_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='origens_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origens',
            },
        ),
        migrations.AddField(
            model_name='orgaos',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orgaos_secretaria', to='planejamento.secretarias'),
        ),
        migrations.AddField(
            model_name='orgaos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orgaos_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrcamentosReceitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Previsto')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orcamentosreceitas_created_by', to=settings.AUTH_USER_MODEL)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentosreceitas_fonte', to='planejamento.fontes')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentosreceitas_orcamento', to='planejamento.orcamentos')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentosreceitas_orgao', to='planejamento.orgaos')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentosreceitas_rubrica', to='planejamento.rubricas')),
                ('unidade_orcamentaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentosreceitas_unidade_orcamentaria', to='planejamento.unidadesorcamentarias')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orcamentosreceitas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento de Receitas',
                'verbose_name_plural': 'Orçamento de Receitas',
            },
        ),
        migrations.CreateModel(
            name='OrcamentosDespesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_reduzido', models.CharField(max_length=50, verbose_name='Código Reduzido')),
                ('valor_dotacao_fixado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Fixado na Dotação')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentosdespesas_acao', to='planejamento.acoes')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orcamentosdespesas_created_by', to=settings.AUTH_USER_MODEL)),
                ('elemento_despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentosdespesas_elemento_despesa', to='planejamento.elementosdespesa')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentosdespesas_funcao', to='planejamento.funcoes')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orcamentosdespesas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento de Despesas',
                'verbose_name_plural': 'Orçamento de Despesas',
            },
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='planoplurianual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_planoplurianual', to='planejamento.planoplurianual'),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orcamentos_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ModalidadesAplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modalidadesaplicacao_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modalidadesaplicacao_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modalidadesaplicacao_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modalidade de Aplicação',
                'verbose_name_plural': 'Modalidades de Aplicação',
            },
        ),
        migrations.CreateModel(
            name='GruposNaturezasDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gruposnaturezasdespesa_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gruposnaturezasdespesa_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gruposnaturezasdespesa_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Natureza de Despesa',
                'verbose_name_plural': 'Grupos de Naturezas de Despesa',
            },
        ),
        migrations.AddField(
            model_name='fontes',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fontes_orcamento', to='planejamento.orcamentos'),
        ),
        migrations.AddField(
            model_name='fontes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fontes_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='especies_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especies_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='especies_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
            },
        ),
        migrations.AddField(
            model_name='elementosdespesa',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementosdespesa_orcamento', to='planejamento.orcamentos'),
        ),
        migrations.AddField(
            model_name='elementosdespesa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='elementosdespesa_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CategoriasEconomicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoriaseconomicas_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoriaseconomicas_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoriaseconomicas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria Econômica',
                'verbose_name_plural': 'Categorias Econômicas',
            },
        ),
        migrations.CreateModel(
            name='Alineas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alineas_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alineas_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alineas_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alínea',
                'verbose_name_plural': 'Alíneas',
            },
        ),
        migrations.CreateModel(
            name='AcoesTipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acoestipos_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acoestipos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Ação',
                'verbose_name_plural': 'Tipos de Ações',
            },
        ),
        migrations.AddField(
            model_name='acoes',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_funcao', to='planejamento.funcoes'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_orcamento', to='planejamento.orcamentos'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_orgao', to='planejamento.orgaos'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_programa', to='planejamento.programas'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='sub_funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_sub_funcao', to='planejamento.subfuncoes'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_tipo', to='planejamento.acoestipos'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='unidade_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_unidade_orcamentaria', to='planejamento.unidadesorcamentarias'),
        ),
        migrations.AddField(
            model_name='acoes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acoes_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
