# Generated by Django 3.2 on 2022-03-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasControle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('controla_limite_mensal', models.IntegerField(choices=[(0, 'Nao'), (1, 'Sim')], verbose_name='Controla Limite Mensal?')),
                ('instrumento_despesa', models.IntegerField(choices=[(0, 'Nao'), (1, 'Sim')], verbose_name='Executada por meio de Instrumento de Despesa?')),
            ],
            options={
                'verbose_name': 'Conta de Controle',
                'verbose_name_plural': 'Contas de Controle',
            },
        ),
        migrations.CreateModel(
            name='ContasControleAcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Ação vinculada a Conta de Controle',
                'verbose_name_plural': 'Ações Vinculadas a Conta de Controle',
            },
        ),
        migrations.CreateModel(
            name='ContasControleElementosDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Elemento de despesa vinculado a Conta de Controle',
                'verbose_name_plural': 'Elementos de Despesa Vinculados a Conta de Controle',
            },
        ),
        migrations.CreateModel(
            name='ContasControleLimites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Nao Definido')], verbose_name='Status')),
                ('tipo', models.IntegerField(choices=[(1, 'Projeto'), (2, 'Atividade')], verbose_name='Tipo')),
                ('valor_jan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Janeiro')),
                ('valor_fev', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Fevereiro')),
                ('valor_mar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Março')),
                ('valor_abr', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Abril')),
                ('valor_mai', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Maio')),
                ('valor_jun', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Junho')),
                ('valor_jul', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Julho')),
                ('valor_ago', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Agosto')),
                ('valor_set', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Setembro')),
                ('valor_out', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Outubro')),
                ('valor_nov', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Novembro')),
                ('valor_dez', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Dezembro')),
            ],
            options={
                'verbose_name': 'Limite da Conta de Controle',
                'verbose_name_plural': 'Limites das Contas de Controle',
            },
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.IntegerField(choices=[(1, 'Projeto'), (2, 'Atividade')], verbose_name='Tipo')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('prazo_de_execucao', models.IntegerField(verbose_name='Prazo de Execução (em Meses)')),
                ('status', models.IntegerField(choices=[(1, 'Nao Definido')], verbose_name='Status')),
                ('valor_jan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Janeiro')),
                ('valor_fev', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Fevereiro')),
                ('valor_mar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Março')),
                ('valor_abr', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Abril')),
                ('valor_mai', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Maio')),
                ('valor_jun', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Junho')),
                ('valor_jul', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Julho')),
                ('valor_ago', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Agosto')),
                ('valor_set', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Setembro')),
                ('valor_out', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Outubro')),
                ('valor_nov', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Novembro')),
                ('valor_dez', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Dezembro')),
                ('data_aprovacao', models.DateTimeField(verbose_name='Data de Aprovação')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Término')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='DespesasAcompanhamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Acompanhamento da Despesa',
                'verbose_name_plural': 'Acompanhamentos da Despesa',
            },
        ),
        migrations.CreateModel(
            name='DespesasArquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('arquivo', models.CharField(max_length=255, verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Arquivo da Despesa',
                'verbose_name_plural': 'Arquivos da Despesa',
            },
        ),
        migrations.CreateModel(
            name='DespesasFontes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Fonte da Despesa',
                'verbose_name_plural': 'Fontes da Despesa',
            },
        ),
        migrations.CreateModel(
            name='DespesasHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.IntegerField(choices=[(1, 'Projeto'), (2, 'Atividade')], verbose_name='Tipo')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('prazo_de_execucao', models.IntegerField(verbose_name='Prazo de Execução (em Meses)')),
                ('status', models.IntegerField(choices=[(1, 'Nao Definido')], verbose_name='Status')),
                ('valor_jan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Janeiro')),
                ('valor_fev', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Fevereiro')),
                ('valor_mar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Março')),
                ('valor_abr', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Abril')),
                ('valor_mai', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Maio')),
                ('valor_jun', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Junho')),
                ('valor_jul', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Julho')),
                ('valor_ago', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Agosto')),
                ('valor_set', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Setembro')),
                ('valor_out', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Outubro')),
                ('valor_nov', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Novembro')),
                ('valor_dez', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Dezembro')),
                ('data_aprovacao', models.DateTimeField(verbose_name='Data de Aprovação')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Término')),
            ],
            options={
                'verbose_name': 'Histórico da Despesa',
                'verbose_name_plural': 'Histórico da Despesa',
            },
        ),
        migrations.CreateModel(
            name='PreEmpenhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('ano_exercicio', models.CharField(max_length=4, verbose_name='Ano de Exercício')),
                ('natureza', models.IntegerField(choices=[(0, 'Nao informado'), (1, 'Ordinario'), (2, 'Anulacao'), (3, 'Suplementacao')], verbose_name='Natureza')),
                ('num_ned_ordinaria', models.CharField(max_length=50, verbose_name='Número do Empenho Ordinário')),
                ('num_processo', models.CharField(max_length=20, verbose_name='Número do Processo')),
                ('tipo_instrumento_despesa', models.IntegerField(choices=[(1, 'Pessoal'), (2, 'Diarias'), (3, 'Suprimento de Fundos'), (4, 'Contratos'), (5, 'Convenios'), (6, 'Despesas sem Contrato')], verbose_name='Tipo de Instrumento de Despesa')),
                ('tipo_instrumento_receita', models.IntegerField(choices=[(0, 'Nao possui'), (1, 'Contratos'), (2, 'Convenios')], verbose_name='Tipo de Instrumento de Receita')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('status', models.IntegerField(choices=[(1, 'Nao Definido')], verbose_name='Status')),
                ('conta_controle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_conta_controle', to='controle.contascontrole')),
                ('contrato_despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_contrato_despesa', to='contratos.contratos')),
                ('contrato_receita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_contrato_receita', to='contratos.contratos')),
            ],
            options={
                'verbose_name': 'Pré-Empenho',
                'verbose_name_plural': 'Pré-Empenhos',
            },
        ),
        migrations.CreateModel(
            name='PrePagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('status', models.IntegerField(choices=[(1, 'Nao Definido')], verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prepagamentos_created_by', to=settings.AUTH_USER_MODEL)),
                ('pre_empenho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepagamentos_pre_empenho', to='controle.preempenhos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prepagamentos_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pré-Pagamento',
                'verbose_name_plural': 'Pré-Pagamentos',
            },
        ),
    ]
