# Generated by Django 3.2 on 2022-03-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_basicos', '0001_initial'),
        ('despesas_sem_contrato', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle', '0001_initial'),
        ('planejamento', '0001_initial'),
        ('convenios', '0001_initial'),
        ('execucao_orcamentaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preempenhos',
            name='convenio_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_convenio_despesa', to='convenios.convenios'),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='convenio_receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_convenio_receita', to='convenios.convenios'),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preempenhos_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='credor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_credor', to='execucao_orcamentaria.credores'),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_despesa', to='controle.despesas'),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='despesa_sem_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_despesa_sem_contrato', to='despesas_sem_contrato.despesassemcontrato'),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='dotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_dotacao', to='planejamento.orcamentosdespesas'),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_orgao', to='planejamento.orgaos'),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='unidade_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preempenhos_unidade_orcamentaria', to='planejamento.unidadesorcamentarias'),
        ),
        migrations.AddField(
            model_name='preempenhos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preempenhos_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesashistorico',
            name='conta_controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesashistorico_conta_controle', to='controle.contascontrole'),
        ),
        migrations.AddField(
            model_name='despesashistorico',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesashistorico_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesashistorico',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesashistorico_despesa', to='controle.despesas'),
        ),
        migrations.AddField(
            model_name='despesashistorico',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesashistorico_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesasfontes',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesasfontes_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesasfontes',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesasfontes_despesa', to='controle.despesas'),
        ),
        migrations.AddField(
            model_name='despesasfontes',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesasfontes_fonte', to='planejamento.fontes'),
        ),
        migrations.AddField(
            model_name='despesasfontes',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesasfontes_orcamento', to='planejamento.orcamentos'),
        ),
        migrations.AddField(
            model_name='despesasfontes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesasfontes_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesasarquivos',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesasarquivos_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesasarquivos',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesasarquivos_despesa', to='controle.despesas'),
        ),
        migrations.AddField(
            model_name='despesasarquivos',
            name='tipo_arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesasarquivos_tipo_arquivo', to='cadastros_basicos.arquivostipos'),
        ),
        migrations.AddField(
            model_name='despesasarquivos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesasarquivos_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesasacompanhamentos',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesasacompanhamentos_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesasacompanhamentos',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesasacompanhamentos_despesa', to='controle.despesas'),
        ),
        migrations.AddField(
            model_name='despesasacompanhamentos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesasacompanhamentos_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesas',
            name='conta_controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_conta_controle', to='controle.contascontrole'),
        ),
        migrations.AddField(
            model_name='despesas',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesas_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesas',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despesas_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contascontrolelimites',
            name='conta_controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contascontrolelimites_conta_controle', to='controle.contascontrole'),
        ),
        migrations.AddField(
            model_name='contascontrolelimites',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contascontrolelimites_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contascontrolelimites',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contascontrolelimites_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contascontroleelementosdespesa',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contascontroleelementosdespesa_codigo', to='planejamento.elementosdespesa'),
        ),
        migrations.AddField(
            model_name='contascontroleelementosdespesa',
            name='conta_controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contascontroleelementosdespesa_conta_controle', to='controle.contascontrole'),
        ),
        migrations.AddField(
            model_name='contascontroleelementosdespesa',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contascontroleelementosdespesa_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contascontroleelementosdespesa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contascontroleelementosdespesa_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contascontroleacoes',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contascontroleacoes_acao', to='planejamento.acoes'),
        ),
        migrations.AddField(
            model_name='contascontroleacoes',
            name='conta_controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contascontroleacoes_conta_controle', to='controle.contascontrole'),
        ),
        migrations.AddField(
            model_name='contascontroleacoes',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contascontroleacoes_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contascontroleacoes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contascontroleacoes_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contascontrole',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contascontrole_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contascontrole',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contascontrole_orcamento', to='planejamento.orcamentos'),
        ),
        migrations.AddField(
            model_name='contascontrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contascontrole_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
