# Generated by Django 3.2 on 2022-03-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('fundamentacao', models.TextField(verbose_name='Fundamentação')),
                ('num_documento', models.CharField(max_length=50, verbose_name='Número do Documento')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('classificacao', models.CharField(max_length=50, verbose_name='Classificação')),
                ('num_processo', models.CharField(max_length=50, verbose_name='Número do Processo')),
                ('status', models.IntegerField(choices=[(1, 'Nao Definido')], verbose_name='Status')),
                ('tipo_objeto', models.IntegerField(choices=[(1, 'Nao Definido')], verbose_name='Tipo de Objeto')),
                ('num_sic', models.CharField(max_length=50, verbose_name='Número no Sistema Contratos')),
                ('tipo_modalidade_aquisicao', models.IntegerField(choices=[(0, 'Nao informado'), (1, 'Licitacao'), (2, 'Dispensa'), (3, 'Inexigibilidade')], verbose_name='Tipo da Modalidade de Aquisição')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Original')),
                ('valor_contrapartida', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Contra-Partida')),
                ('data_assinatura', models.DateTimeField(verbose_name='Data de Assinatura')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de Publicação')),
                ('num_pagina_diario_oficial', models.IntegerField(verbose_name='Página do Diário Oficial')),
                ('data_publicacao_portal', models.DateTimeField(verbose_name='Data de Publicação no Portal')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('vigencia', models.IntegerField(verbose_name='Vigência')),
                ('data_termino', models.DateTimeField(verbose_name='Data de Término')),
                ('arquivo', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('concluido_divida', models.BooleanField(verbose_name='Concluído com dívida?')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='ContratosAditivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('data_assinatura', models.DateTimeField(verbose_name='Data de Assinatura')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de Publicação')),
                ('num_pagina_diario_oficial', models.IntegerField(verbose_name='Página do Diário Oficial')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('vigencia', models.IntegerField(verbose_name='Vigência')),
                ('data_termino', models.DateTimeField(verbose_name='Data de Término')),
                ('num_documento', models.CharField(max_length=50, verbose_name='Número do Documento')),
                ('objeto', models.CharField(max_length=500, verbose_name='Objeto')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('valor_contrapartida', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Contra-Partida')),
                ('arquivo', models.CharField(max_length=255, verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Aditivo do Contrato',
                'verbose_name_plural': 'Aditivos do Contrato',
            },
        ),
        migrations.CreateModel(
            name='ContratosArquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('nome_arquivo', models.CharField(max_length=500, verbose_name='Nome do Arquivo')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('arquivo', models.CharField(max_length=255, verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Arquivo do Contrato',
                'verbose_name_plural': 'Arquivos do Contrato',
            },
        ),
        migrations.CreateModel(
            name='ContratosClassificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Classificação do Contrato',
                'verbose_name_plural': 'Classificações do Contrato',
            },
        ),
        migrations.CreateModel(
            name='ContratosContasControle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conta de Controle do Contrato',
                'verbose_name_plural': 'Contas de Controle do Contrato',
            },
        ),
        migrations.CreateModel(
            name='ContratosDotacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosdotacoes_contrato', to='contratos.contratos')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratosdotacoes_created_by', to=settings.AUTH_USER_MODEL)),
                ('dotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosdotacoes_dotacao', to='planejamento.orcamentosdespesas')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosdotacoes_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratosdotacoes_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dotação do Contrato',
                'verbose_name_plural': 'Dotações do Contrato',
            },
        ),
        migrations.CreateModel(
            name='ContratosCronogramaMensal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('valor_jan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Janeiro')),
                ('valor_fev', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Fevereiro')),
                ('valor_mar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Março')),
                ('valor_abr', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Abril')),
                ('valor_mai', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Maio')),
                ('valor_jun', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Junho')),
                ('valor_jul', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Julho')),
                ('valor_ago', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Agosto')),
                ('valor_set', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Setembro')),
                ('valor_out', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Outubro')),
                ('valor_nov', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Novembro')),
                ('valor_dez', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Dezembro')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratoscronogramamensal_contrato', to='contratos.contratos')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratoscronogramamensal_created_by', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratoscronogramamensal_orcamento', to='planejamento.orcamentos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratoscronogramamensal_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cronograma Mensal do Contrato',
                'verbose_name_plural': 'Cronogramas Mensais do Contrato',
            },
        ),
    ]
