# Generated by Django 3.2 on 2022-03-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_basicos', '0001_initial'),
        ('contratos', '0001_initial'),
        ('dispositivos_de_contratacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planejamento', '0001_initial'),
        ('controle', '0001_initial'),
        ('execucao_orcamentaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoscontascontrole',
            name='conta_controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratoscontascontrole_conta_controle', to='controle.contascontrole'),
        ),
        migrations.AddField(
            model_name='contratoscontascontrole',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratoscontascontrole_contrato', to='contratos.contratos'),
        ),
        migrations.AddField(
            model_name='contratoscontascontrole',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratoscontascontrole_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratoscontascontrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratoscontascontrole_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosclassificacao',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratosclassificacao_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosclassificacao',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratosclassificacao_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosarquivos',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosarquivos_contrato', to='contratos.contratos'),
        ),
        migrations.AddField(
            model_name='contratosarquivos',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratosarquivos_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosarquivos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosarquivos_tipo', to='cadastros_basicos.arquivostipos'),
        ),
        migrations.AddField(
            model_name='contratosarquivos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratosarquivos_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosaditivos',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosaditivos_contrato', to='contratos.contratos'),
        ),
        migrations.AddField(
            model_name='contratosaditivos',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratosaditivos_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosaditivos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratosaditivos_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratos',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratos',
            name='credor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_credor', to='execucao_orcamentaria.credores'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='dispensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_dispensa', to='dispositivos_de_contratacao.dispensas'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='dispositivo_legal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_dispositivo_legal', to='cadastros_basicos.dispositivoslegais'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='inexigibilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_inexigibilidade', to='dispositivos_de_contratacao.inexigibilidades'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='licitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_licitacao', to='dispositivos_de_contratacao.licitacoes'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='unidade_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_unidade_orcamentaria', to='planejamento.unidadesorcamentarias'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
